version: '3'

tasks:
  dev:
    deps: [server,fontend,soap]
    paralel: true

  server:
    dir: ./Server
    cmd: go run .
    internal: true

  fontend:
    dir: ./Desktop
    cmd: wails dev
    internal: true

  soap:
    dir: ./SoapService/WebsiteContactsService
    cmd: dotnet run
    internal: true